[project]
name = "photoframe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "esptool>=5.1.0",
    "frame-ha-bridge",
    "websockets>=13,<15"
]

[tool.uv.sources]
frame-ha-bridge = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/frame-ha-bridge",
]

[build-system]
requires = ["uv_build>=0.11.7,<0.12"]
build-backend = "uv_build"